version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crm-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: crm_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - crm-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/crm_db
      - PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mongodb_data:
