# CI-owned image state for crm-app. Written by .github/workflows/ci.yml
# on every successful build. Do not hand-edit.
crm-app:
  image:
    tag: "v1.0.0-aabe5dc"
    digest: "sha256:32ad06828905585a653820d6798eba41e6cb2f4e8bbbe9b66628d21f9fec5549"
