# CI-owned image state for crm-app. Written by .github/workflows/ci.yml
# on every successful build. Do not hand-edit.
crm-app:
  image:
    tag: "v1.0.0-44368c5"
    digest: "sha256:b3c47541f4caab28e2358a4ef832455baf26f0c5b612a282818f54bb0b488245"
