# CI-owned image state for crm-app. Written by .github/workflows/ci.yml
# on every successful build. Do not hand-edit.
crm-app:
  image:
    tag: "v1.0.0-eb17f91"
    digest: "sha256:0020ccde863c89e65e144de349b5a92d5ef161c7cef850a0cfddac01d0e9026f"
