# CI-owned image state for crm-app. Written by .github/workflows/ci.yml
# on every successful build. Do not hand-edit.
crm-app:
  image:
    tag: "v1.0.0-30610fc"
    digest: "sha256:d60f59d509de36b877c95c103d5b88e4b9a6bbcc2a2f467a6fe690d915bcc0f7"
