name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: crm-app
  EKS_CLUSTER_NAME: develeap-eks-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Stage 1: Clone/Pull
      - name: Checkout code
        uses: actions/checkout@v4

      # Stage 2: Build the application (not Docker image)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 3: Unit tests
      - name: Run unit tests
        run: |
          pip install pytest
          pytest test_app.py -v

      # Stage 4: Package (Build Docker image)
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} ${{ env.ECR_REPOSITORY }}:latest

      # Stage 5: End-to-End Testing
      - name: Start test environment
        run: |
          docker compose -f docker-compose.test.yml up -d
          echo "Waiting for services to be ready..."
          sleep 20

      - name: Run E2E tests
        run: |
          chmod +x test_e2e.sh
          ./test_e2e.sh

      - name: Stop test environment
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v

      # Stage 6: Publish to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          echo "Image pushed: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"

      # Stage 7: Deploy to K8S cluster
      - name: Check if EKS cluster exists
        id: check-cluster
        run: |
          if aws eks describe-cluster --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install kubectl
        if: steps.check-cluster.outputs.exists == 'true'
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        if: steps.check-cluster.outputs.exists == 'true'
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Check if deployment exists
        if: steps.check-cluster.outputs.exists == 'true'
        id: check-deployment
        run: |
          if kubectl get deployment crm-app -n default >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Kubernetes (update existing)
        if: steps.check-cluster.outputs.exists == 'true' && steps.check-deployment.outputs.exists == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/crm-app crm-app=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG -n default
          kubectl rollout status deployment/crm-app -n default
          echo "Deployment updated successfully!"

      - name: Skip deployment (not deployed yet)
        if: steps.check-cluster.outputs.exists == 'true' && steps.check-deployment.outputs.exists == 'false'
        run: |
          echo "Deployment 'crm-app' does not exist yet. Skipping kubectl set image."
          echo "Please deploy the application manually first using kubectl apply."

      - name: Skip deployment (cluster not found)
        if: steps.check-cluster.outputs.exists == 'false'
        run: |
          echo "EKS cluster '${{ env.EKS_CLUSTER_NAME }}' not found. Skipping deployment."

      - name: Verify deployment
        if: steps.check-cluster.outputs.exists == 'true' && steps.check-deployment.outputs.exists == 'true'
        run: |
          kubectl get pods -n default
          kubectl get services -n default
